apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yourname-santapp-ruler-rwx
  namespace: ucsb-opus-lab
  labels:
    app.kubernetes.io/name: yourname-santapp-ruler
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: santapp-ruler-default-2tasks-6methods-100p-8k
    owner: yourname
spec:
  storageClassName: rook-cephfs
  accessModes: [ReadWriteMany]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
