apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: researcher-santa-ruler-pvc
  namespace: ucsb-opus-lab
  labels:
    app.kubernetes.io/name: santa-ruler
    benchmark-owner: researcher
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 50Gi
